version: '3.6'
services:
  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - atelier-amelie-core
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  atelier-amelie-core:
